name: test-and-build
on: [push]
jobs:
  test-and-build-api-and-client:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.15.0]
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install nx -g
      - run: nx run-many --all --target=test
      - run: nx build api
      - run: nx build client
